### ISSUE TITLE
Tema para charlar en la JSConf.co

### ISSUE THREAD

**Issue by rianby64** [rianby64/karma-jasmine-feature-example#1]
Tengo una pregunta que hacerte, @epsanchezma ... Que tan de moda esta en Colombia trabajar el tema de CucumberJS bajo Karma?

**Comment by epsanchezma** [comment]
Sinceramente no había escuchado de esta herramienta de testing con lenguaje natural, tampoco he escuchado de personas que lo estén usando (pero seria bueno hacer una pequeña encuesta o algo para corroborar). 
Si estas pensando en un tema para JSConf sobre esto, estaría bueno que no solo fuese como un walkthrough sino como un experimento con algo más.
Lamento no ser de mucha ayuda, saludos.

**Comment by rianby64** [comment]
Bien... falta de interés por ambas partes.

**Comment by rianby64** [comment]
@epsanchezma me quedó sonando el "elixir"... En que me lo aconsejas? hay manera de que charlemos sobre JavaScript y Elixir? Quedo muy atento! Feliz dia!
